Iter15
sub3er0/urlShorteningService pull request #15
Opened 2024-08-27 21:27 UTC by sub3er0

2024-09-03 01:44 UTC, vokinneberg requested changes
Поздравляю с первым ревью четвёртого спринта! 🎉 В этом спринте мы коснулись, наверное, самых сложных тем — многопоточности и криптографии. Хочу сделать несколько предложений по улучшению и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Код функционален, корректен и проходит тесты! 🚀
2. Ты лаконично встроил изменения в структуру существующего приложения. 👍
3. Ты покрыл тестами новые компоненты. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Дело в том, что твоя реализация не соответствует постановке задачи: *В случае успешного приёма запроса хендлер должен возвращать HTTP-статус 202 Accepted. Фактический результат удаления может происходить позже — оповещать пользователя об успешности или неуспешности не нужно.*
    
    В твоём случае мы всё же ожидаем завершения всех горутин перед тем, как вернуть ответ пользователю. Мне кажется, простая реализация с использованием паттерна `fanIn` может выглядеть следующим образом.
    
    - При старте приложения мы запускаем горутину (воркер) в методе `mail`, которая читает из канала (буфера), когда он наполняется, и для всех задач на выполнение из буфера формирует батч, который выполняет, обновляя URLs. Потом приостанавливает работу, пока буфер опять не наполнится.
    - Хендлер, получив запрос на удаление, отправляет задачи на удаление в канал, из которого читает наша горутина, и сразу (не дожидаясь выполнения) возвращает ответ пользователю.
2. Так как мы модифицируем схему БД в существующем приложении, база уже может быть создана. Поэтому я бы рекомендовал добавлять колонку либо при помощи отдельной операции, либо использовать миграции. В любом случае решение должно быть обратно совместимо с существующим кодом.
3. Было бы здорово реализовать тесты новых сценариев.
4. Я бы предложил разделить как интерфейсы, так и реализации для пользователя и для URL.

2024-09-03 01:44 UTC, vokinneberg commented on internal/cookie/cookie_handler.go
> +			if r.Method == "GET" && r.URL.Path == "/api/user/urls" {
Middleware стоит реализовывать максимально generic без привязки к конкретному пути, и навешивать его на те пути, для которых он требуется.

2024-09-03 01:44 UTC, vokinneberg commented on internal/cookie/cookie_handler.go
> +	//decodedData, err := base64.RawURLEncoding.DecodeString(data)
Не стоит оставлять закомментированный код в репозитории. Это засоряет кодовую базу. Если без этого нельзя обойтись, стоит оставить комментарий почему это так.

2024-09-03 01:44 UTC, vokinneberg commented on internal/shortener/shortener.go
> +	if r.Method != http.MethodDelete {
Если мы используем `chi` это проверка лишняя, так как фреймворк выполнит ее автоматически.

2024-09-03 01:44 UTC, vokinneberg commented on internal/shortener/shortener.go
> +	for err := range errChan {
Дело в том, что твоя реализация не соответствует постановке задачи: _В случае успешного приёма запроса хендлер должен возвращать HTTP-статус 202 Accepted. Фактический результат удаления может происходить позже — оповещать пользователя об успешности или неуспешности не нужно._

В твоём случае мы всё же ожидаем завершения всех горутин перед тем, как вернуть ответ пользователю. Мне кажется, простая реализация с использованием паттерна `fanIn` может выглядеть следующим образом.

- При старте приложения мы запускаем горутину (воркер) в методе `mail`, которая читает из канала (буфера), когда он наполняется, и для всех задач на выполнение из буфера формирует батч, который выполняет, обновляя URLs. Потом приостанавливает работу, пока буфер опять не наполнится.
- Хендлер, получив запрос на удаление, отправляет задачи на удаление в канал, из которого читает наша горутина, и сразу (не дожидаясь выполнения) возвращает ответ пользователю.

2024-09-03 01:44 UTC, vokinneberg commented on internal/shortener/shortener.go
> +	if r.Method != http.MethodPost {
Если мы используем chi это проверка лишняя, так как фреймворк выполнит ее автоматически.

2024-09-03 01:44 UTC, vokinneberg commented on internal/shortener/shortener_test.go
> +	"github.com/sub3er0/urlShorteningService/internal/cookie"
Было бы здорово реализовать тесты новых сценариев.

2024-09-03 01:44 UTC, vokinneberg commented on internal/storage/db_storage.go
> +	CREATE TABLE IF NOT EXISTS urls (
Так как мы модифицируем схему БД в существующем приложении, база уже может быть создана. Поэтому я бы рекомендовал добавлять колонку либо при помощи отдельной операции, либо использовать миграции. В любом случае решение должно быть обратно совместимо с существующим кодом.

2024-09-03 01:44 UTC, vokinneberg commented on internal/storage/file_storage.go
> +func (fs *FileStorage) DeleteUserUrls(uniqueID string, shortURLS []string) error {
Было бы здорово реализовать обратную совместимость во всех типах хранилищ.

2024-09-03 01:44 UTC, vokinneberg commented on internal/storage/in_memory_storage.go
> +func (ims *InMemoryStorage) DeleteUserUrls(uniqueID string, shortURLS []string) error {
Было бы здорово реализовать обратную совместимость во всех типах хранилищ.

2024-09-03 01:44 UTC, vokinneberg commented on internal/storage/url_storage_interface.go
> +type URLStorage interface {
Я бы предложил разделить как интерфейсы, так и реализации для пользователя и для URL.

2024-09-05 21:21 UTC, sub3er0 commented on internal/cookie/cookie_handler.go
> +			if r.Method == "GET" && r.URL.Path == "/api/user/urls" {
исправлено

2024-09-05 21:21 UTC, sub3er0 commented on internal/cookie/cookie_handler.go
> +	//decodedData, err := base64.RawURLEncoding.DecodeString(data)
исправлено

2024-09-05 21:21 UTC, sub3er0 commented on internal/shortener/shortener.go
> +	if r.Method != http.MethodDelete {
исправлено

2024-09-05 21:21 UTC, sub3er0 commented on internal/shortener/shortener.go
> +	for err := range errChan {
исправлено

2024-09-05 21:21 UTC, sub3er0 commented on internal/shortener/shortener.go
> +	if r.Method != http.MethodPost {
исправлено

2024-09-06 04:25 UTC, vokinneberg approved these changes
Поздравляю с успешным завершением четвертого спринта! 🚀 Желаю удачи на выпускном проекте! 🍀

2024-09-06 04:25 UTC, vokinneberg commented on internal/shortener/shortener.go
> +		log.Printf("asdfasdf")
Видимо эта строка добавлена с целью дебага? Стоит наверное ее убрать?

2024-11-01 20:30 UTC, merged