Iter23
sub3er0/urlShorteningService pull request #23
Opened 2024-11-20 02:51 UTC by sub3er0

2024-11-22 02:12 UTC, vokinneberg requested changes
Поздравляю с первым ревью девятого спринта! 🎉 Продолжаем улучшать наше приложение и покрывать его тестами! ⚡ В этом спринте у меня минимум замечаний и предложений по улучшению твоего кода, тем не менее они есть. 🤓

**Сильные стороны твоего PR:**

1. Ты реализовал функционал, требующийся по ТЗ 👍
2. Ты улучшил покрытие кода тестами 🙌

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Не совсем понятно зачем нужна двойная проверка `if cfg.EnableHTTPS || os.Getenv("ENABLE_HTTPS") == "true"`, если на строке 90 в файле `config.go` мы уже проверяем переменную окружения?
2. Не все тесты к сожалению выполнятся. Получаю ошибку при запуске `go test ./... -coverprofile cover && go tool cover -func cover`:
    
    ```
    --- FAIL: TestInitConfig_ValidArgs (0.00s)
        config_test.go:19: 
            	Error Trace:	/Users/a206700522/sources/yandex-praktukum/AlexanderKrainov/urlShorteningService/internal/config/config_test.go:19
            	Error:      	Not equal: 
            	           	expected: "http://localhost:8080/"
            	           	actual  : "http://localhost:8000"
            	           	
            	           	Diff:
            	           	--- Expected
            	           	+++ Actual
            	           	@@ -1 +1 @@
            	           	-http://localhost:8080/
            	           	+http://localhost:8000
            	Test:       	TestInitConfig_ValidArgs
        config_test.go:21: 
            	Error Trace:	/Users/a206700522/sources/yandex-praktukum/AlexanderKrainov/urlShorteningService/internal/config/config_test.go:21
            	Error:      	Not equal: 
            	           	expected: "/path/to/file"
            	           	actual  : "./envStorage.txt"
            	           	
            	           	Diff:
            	           	--- Expected
            	           	+++ Actual
            	           	@@ -1 +1 @@
            	           	-/path/to/file
            	           	+./envStorage.txt
            	Test:       	TestInitConfig_ValidArgs
        config_test.go:22: 
            	Error Trace:	/Users/a206700522/sources/yandex-praktukum/AlexanderKrainov/urlShorteningService/internal/config/config_test.go:22
            	Error:      	Not equal: 
            	           	expected: "user:pass@/dbname"
            	           	actual  : "postgresql://shortner:123456789@localhost:5432/postgres?sslmode=disable"
            	           	
            	           	Diff:
            	           	--- Expected
            	           	+++ Actual
            	           	@@ -1 +1 @@
            	           	-user:pass@/dbname
            	           	+postgresql://shortner:123456789@localhost:5432/postgres?sslmode=disable
            	Test:       	TestInitConfig_ValidArgs
    2024/11/21 21:08:06 Warning: Error opening config file: open config.json: no such file or directory. Using default configuration.
    2024/11/21 21:08:06 Warning: Error decoding config file: invalid argument. Using default configuration.
    2024/11/21 21:08:06 Warning: Error opening config file: open config.json: no such file or directory. Using default configuration.
    2024/11/21 21:08:06 Warning: Error decoding config file: invalid argument. Using default configuration.
    2024/11/21 21:08:06 Warning: Error opening config file: open config.json: no such file or directory. Using default configuration.
    2024/11/21 21:08:06 Warning: Error decoding config file: invalid argument. Using default configuration.
    FAIL
    ```
    

Более детальные комментарии ты найдёшь в PR. 🤓

2024-11-22 02:12 UTC, vokinneberg commented on cmd/shortener/main.go
> +	if cfg.EnableHTTPS || os.Getenv("ENABLE_HTTPS") == "true" {
Не совсем понятно зачем нужна двойная проверка, если на строке 90 в файле `config.go` мы уже проверяем переменную окружения?

2024-11-28 18:47 UTC, sub3er0 commented on cmd/shortener/main.go
> +	if cfg.EnableHTTPS || os.Getenv("ENABLE_HTTPS") == "true" {
![image](https://github.com/user-attachments/assets/a192b3c0-d687-439f-aca1-8688d11f8ab2)
У меня все корректно отрабатывает, непонятно, как в таком случае с тобой добиться одинакового поведения.

2024-11-30 03:16 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью девятого спринта! 🎉 Видимо проблема с тестами была на моей стороне, прошу прощения!

2024-12-03 18:24 UTC, merged