Iter5
sub3er0/urlShorteningService pull request #5
Opened 2024-07-09 14:56 UTC by sub3er0

2024-07-15 15:29 UTC, vokinneberg requested changes
Поздравляю с завершением первого спринта и первым ревью! 🤗 Твой код хорошо структурирован, покрыт тестами, работает и проходит тесты. Отличная работа! 🚀

**Сильные стороны твоего PR:**

1. **Функциональность:** Код функционален и корректен! 🚀
2. **Лаконичность:** Меньше кода - меньше ошибок, тем не менее лаконичность не должна идти в ущерб структуре 🤗
3. **Тестирование:** Реализованы тесты базовых сценариев. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. **Структура сервиса:** По условию задания структура сервиса должна представлять собой набор пакетов и структур, разделённых на слои. В твоем коде уже есть компонент конфига, но я бы рекомендовал выделить отдельный слой для хранилища. 👍
2. **Использование интерфейсов:** Было бы здорово если бы ты реализовал в твоём коде  интерфейсы хранения, что позволяет отделить конкретную реализацию от кода, который использует интерфейс. 👍
3. **Синхронизация доступа** **к хранилищу.** На будущее стоит подумать, как будет себя вести код при конкурентной обработке нескольких запросов и как можно синхронизировать доступ к хранилищу.
4. **Комментарии:** Было бы здорово, если бы ты добавил комментарии в коде там, где есть сложные места, требующие пояснения, а также для публичных методов.
5. **Тестирование:** Стоит добавить информативные сообщения о том, что пошло не так, и что ожидалось в тестах.

2024-07-15 15:29 UTC, vokinneberg commented on cmd/config/config.go
> +package config
👍 за реализацию конфига в виде отдельного компонента.

2024-07-15 15:29 UTC, vokinneberg commented on cmd/shortener/main.go
> +		return
Рекомендую залогировать ошибку и вернуть завершить процесс при помощи `os.Exit(1)`.
```suggestion
		log.Fatalf("Error while initializing config: %v", err)
```

2024-07-15 15:29 UTC, vokinneberg commented on cmd/shortener/main.go
> +		return
Рекомендую залогировать ошибку и вернуть завершить процесс при помощи os.Exit(1).
```suggestion
		log.Fatalf("Error starting server: %s", err)
```

2024-07-15 15:29 UTC, vokinneberg commented on cmd/shortener/main.go
> +	if r.Method != http.MethodPost {
Эта проверка не обязательна в случае использования мультиплексера `chi`, так как он сам автоматически обработает такую ситуацию и вернет код ответа.

2024-07-15 15:29 UTC, vokinneberg commented on cmd/shortener/main.go
> +	}
Не стоит забывать закрывать тело запроса после чтения.

```suggestion
	body, err := io.ReadAll(r.Body)

	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	defer r.Body.Close()
```

2024-07-15 15:29 UTC, vokinneberg commented on cmd/shortener/main.go
> +	for k, v := range us.urls {
👍 за проверку  на то, что URL уже есть в хранилище.

Мне кажется, тут можно немного улучшить работу этого кода, если реализовать компонент хранилища, который инкапсулирует логику проверки на существование URL внутри одного метода и будет возвращать существующий URL, если он уже есть, или добавлять его, если его еще нет.

2024-07-15 15:29 UTC, vokinneberg commented on cmd/shortener/main_test.go
> +func TestURLShortener_PostHandler(t *testing.T) {
Стоит добавить кейс, когда мы пытаемся создать линк для уже существующего URL и проверить, что он такой же как в первый раз?

2024-07-15 15:29 UTC, vokinneberg commented on cmd/shortener/main_test.go
> +	assert.Equal(t, http.StatusCreated, w.Code)
Хотя это и не является ошибкой или некорректным использованием, разработчики Go не рекомендуют использовать сторонние assert библиотеки потому что это либо останавливает тест раньше времени (если вызовы используют `t.Fatalf` или `panic`), либо упускает интересную информацию о том, что тест сделал правильно. Это также заставляет assert библиотеку создавать совершенно новый подъязык вместо использования существующего языка программирования (самого Go). https://go.dev/wiki/TestComments

2024-07-15 15:29 UTC, vokinneberg commented on cmd/shortener/main_test.go
> +	assert.Contains(t, body, "http://localhost")
Было бы здорово добавить информативное сообщение в тесты о том, что ожидалось или что прошло не так. 
```suggestion
	assert.Contains(t, body, "http://localhost", "http://localhost should be in the response body")
```

2024-07-17 14:01 UTC, sub3er0 commented on cmd/shortener/main.go
> +	if r.Method != http.MethodPost {
Без проверки не проходит тест на неправильный метод, падает эксепшн invalid memory address or nil pointer dereference (нет body)

2024-07-17 14:07 UTC, sub3er0 commented on cmd/shortener/main_test.go
> +	assert.Equal(t, http.StatusCreated, w.Code)
Судя по обсуждениям в чате, я так понял, что можно оставить, как есть?

2024-07-17 14:12 UTC, sub3er0 commented on cmd/shortener/main_test.go
> +	assert.Contains(t, body, "http://localhost")
исправлено

2024-07-17 14:12 UTC, sub3er0 commented on cmd/shortener/main_test.go
> +func TestURLShortener_PostHandler(t *testing.T) {
исправлено

2024-07-17 14:12 UTC, sub3er0 commented on cmd/shortener/main.go
> +	for k, v := range us.urls {
исправлено

2024-07-17 14:12 UTC, sub3er0 commented on cmd/shortener/main.go
> +	}
исправлено

2024-07-17 14:12 UTC, sub3er0 commented on cmd/shortener/main.go
> +		return
исправлено

2024-07-17 14:12 UTC, sub3er0 commented on cmd/shortener/main.go
> +		return
исправлено

2024-07-19 21:26 UTC, vokinneberg commented on cmd/shortener/main.go
> +	if r.Method != http.MethodPost {
ОК, давай пока оставим это и разберемся в следующей итерации.

2024-07-19 21:28 UTC, vokinneberg commented on cmd/shortener/main_test.go
> +	assert.Equal(t, http.StatusCreated, w.Code)
Конечно, моя цель показать разные варианты реализации. 👍

2024-07-19 21:29 UTC, vokinneberg approved these changes
Привет 👋, вижу ты реализовал улучшения по моим комментариям. Здорово! 👍 Поздравляю с завершением первого спринта и завершением первого ревью! 🤗 Отличная работа! 🚀

2024-08-02 08:38 UTC, merged